name: Create Project Branch

on:
  project_card:
    types: [moved]

jobs:
  create-branch:
    name: Create branch for Issue
    runs-on: ubuntu-latest
    steps:
      - name: Get project column name
        id: project_column
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        uses: octokit/request-action@v1.x
        with:
          route: GET ${{github.event.project_card.column_url}}
          Authorization: token ${{secrets.GITHUB_TOKEN}}
          mediaType: '{"previews": ["inertia"]}'
      - run: echo "toJson(${{github.event}})"
      - name: Parse to JSON
        id: json
        uses: gr2m/get-json-paths-action@v1.x
        with:
          json: ${{steps.project_column.outputs.data}}
          name: "name"
          rep: "repository.full_name"
      - name: Create branch
        if: steps.json.outputs.name == 'In progress'
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        uses: peterjgrainger/action-create-branch@v1.0.0
        with:
          branch: ${{github.event.project_card.node_id}}
      # - name: Assign user to issue
      #   if: steps.json.outputs.name == 'In progress'
      #   env:
      #     GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      #   uses: octokit/request-action@v1.x
      #   with:
      #     route: PATCH /repos/