name: Create Project Branch

on:
  project_card:
    types: [moved]

jobs:
  create-branch:
    name: Create branch for issue
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
    steps:
      - name: Get project column name
        id: project_column
        uses: korti11/moved-to-column@v0.1
      - name: Create branch
        if: steps.project_column.outputs.column_name == 'In progress'
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        uses: peterjgrainger/action-create-branch@v1.0.0
        with:
          branch: ${{github.event.project_card.node_id}}