name: Create Project Branch

on:
  project_card:
    types: [moved]

jobs:
  create-branch:
    name: Create branch for Issue
    runs-on: ubuntu-latest
    steps:
      - name: Create branch
      uses: peterjgrainger/action-create-branch@v1.0.0
      with:
        branch: 'new-test'