name: Create Project Branch

on:
  project_card:
    types: [moved]

jobs:
  create-branch:
    name: Create branch for Issue
    runs-on: ubuntu-latest
    steps:
      - name: Get project column name
        id: project_column
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        uses: octokit/request-action@v1.x
        with:
          route: GET ${{github.event.project_card.column_url}}
          Authorization: token ${{secrets.GITHUB_TOKEN}}
          mediaType: '{"previews": ["inertia"]}'
      - name: Parse to JSON
        id: json
        uses: gr2m/get-json-paths-action@v1.x
        with:
          json: ${{steps.project_column.outputs.data}}
          name: "name"
      - run: echo ${{steps.json.outputs.name}}
      - run: echo ${{env.COLUMN_NAME}}
        env:
          COLUMN_NAME: ${{'In progress'}}
      - name: Create branch
        if: steps.json.outputs.name == env.COLUMN_NAME
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          COLUMN_NAME: ${{'In progress'}}
        uses: peterjgrainger/action-create-branch@v1.0.0
        with:
          branch: ${{github.event.project_card.node_id}}